# Use postgres/example user/password credentials
version: '3.1'

services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,sqs
      - AWS_DEFAULT_REGION=us-east-2
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
      # - "4572:4572" Old S3 port
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata